### ISSUE TITLE
Specify domain

### ISSUE THREAD

**Issue by Coldfirex** [TrimarcJake/BlueTuxedo#17]
Howdy,
How would I specify a particular domain to use?  I am testing out in a scenario that has a few domain trusts (including one that is down), and it is taking very long to error out on these remote domains.
Thanks!

**Comment by TrimarcJake** [comment]
Hi! This is completely untested, but you should be able to do

Invoke-BlueTuxedo -Forest <fqdn of remote forest>

Please let me know your results!

Heads up: if you aren't running BT with EA-level privileges in the remote forest, you will have really weird results.

**Comment by Coldfirex** [comment]
That seemed to work, thanks!

**Comment by TrimarcJake** [comment]
Oh sweet! Thanks for testing. Okay for me to close?

**Comment by Coldfirex** [comment]
Yes, thanks!

**Comment by TrimarcJake** [comment]
You're welcome! And thanks for being so exuberant!
